import { GoogleGenAI } from "@google/genai";
import { randomUUID } from "node:crypto";
import { ArtifactRequest, ArtifactType, TravelArtifact } from "@/lib/travel-types";

const OMNI_MODEL = process.env.OMNI_FLASH_MODEL || "gemini-omni-flash-preview";

const visualArtifactTypes = new Set<ArtifactType>([
  "phrase_card",
  "route_card",
  "menu_explainer",
  "etiquette_note",
  "alert",
]);

export function shouldUseOmniFlash(type: ArtifactType) {
  return visualArtifactTypes.has(type);
}

export async function createOmniVisualArtifact(
  request: ArtifactRequest
): Promise<TravelArtifact> {
  const now = new Date().toISOString();
  const enabled = process.env.OMNI_FLASH_ENABLED === "true";
  const apiKey = process.env.GEMINI_API_KEY;

  if (!enabled) {
    return {
      id: randomUUID(),
      type: request.type,
      title: "Omni Flash visual layer disabled",
      body:
        "Set OMNI_FLASH_ENABLED=true and GEMINI_API_KEY to create visual/audio travel outputs with Gemini Omni Flash.",
      status: "disabled",
      runtime: "omni-disabled",
      createdAt: now,
    };
  }

  if (!apiKey) {
    return {
      id: randomUUID(),
      type: request.type,
      title: "Omni Flash API key missing",
      body:
        "GEMINI_API_KEY is not set. Visual travel card creation requires Gemini Omni Flash.",
      status: "missing-api-key",
      runtime: "omni-disabled",
      createdAt: now,
    };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const omni = ai as unknown as {
      interactions: {
        create(args: Record<string, unknown>): Promise<{
          id?: string;
          model?: string;
          status?: string;
          output_video?: { data?: string; mime_type?: string };
        }>;
      };
    };
    const interaction = await omni.interactions.create({
      model: OMNI_MODEL,
      input: buildOmniPrompt(request),
      response_format: {
        type: "video",
        aspect_ratio: "9:16",
      },
      generation_config: {
        video_config: {
          task: "text_to_video",
        },
      },
    });
    const videoData = interaction.output_video?.data;
    const mimeType = interaction.output_video?.mime_type || "video/mp4";

    return {
      id: randomUUID(),
      type: request.type,
      title: omniTitle(request.type),
      body: videoData
        ? "Generated by Gemini Omni Flash. The visual output is attached below."
        : `Gemini Omni Flash returned no video payload. Status: ${
            interaction.status || "unknown"
          }.`,
      status: videoData ? "ready" : "error",
      runtime: "gemini-omni-flash",
      media: videoData
        ? {
            kind: "video",
            mimeType,
            dataUrl: `data:${mimeType};base64,${videoData}`,
            model: interaction.model || OMNI_MODEL,
            interactionId: interaction.id,
          }
        : undefined,
      createdAt: now,
    };
  } catch (error) {
    return {
      id: randomUUID(),
      type: request.type,
      title: "Omni Flash generation failed",
      body:
        error instanceof Error
          ? `Gemini Omni Flash failed visibly: ${error.message}`
          : "Gemini Omni Flash failed visibly.",
      status: "error",
      runtime: "gemini-omni-flash",
      createdAt: now,
    };
  }
}

function buildOmniPrompt(request: ArtifactRequest) {
  return [
    "Create a short, readable travel companion visual output for a phone screen.",
    "Use clean text, simple composition, and practical travel guidance.",
    "Do not invent safety-critical facts beyond the supplied context.",
    `Artifact type: ${request.type}`,
    `User request: ${request.prompt}`,
    request.context ? `Context: ${request.context}` : "Context: none supplied",
  ].join("\n");
}

function omniTitle(type: ArtifactType) {
  const titles: Record<ArtifactType, string> = {
    phrase_card: "Omni Flash phrase card",
    route_card: "Omni Flash route card",
    menu_explainer: "Omni Flash menu explainer",
    booking_summary: "Booking summary",
    etiquette_note: "Omni Flash etiquette note",
    alert: "Omni Flash travel alert",
  };
  return titles[type];
}
